variables:
  VAULT_AUTH_ROLE: cio-lambda-proxy

stages:
  - lint
  - build
  - test
  - tf plan
  - deploy
  - ops

lint:
  image: python:3.9-bookworm
  stage: lint
  allow_failure: true
  variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/pip-cache"
  script:
    - pip install --upgrade pip>=25.0 setuptools>=78.1.1
    - pip install poetry
    - poetry config virtualenvs.create false
    - poetry install --with dev
    - make lint
  cache:
    key: "$CI_JOB_NAME"
    paths:
      - pip-cache/

build:
  image: python:3.9-bookworm
  stage: build
  variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/pip-cache"
  script:
    - apt-get update && apt-get install -y zip
    - pip install --upgrade pip>=25.0 setuptools>=78.1.1
    - pip install poetry
    - poetry config virtualenvs.create false
    - poetry self add poetry-plugin-export
    - make build
  artifacts:
    paths:
      - lambda-package.zip
  cache:
    key: "$CI_JOB_NAME"
    paths:
      - pip-cache/

test:
  image: python:3.9-bookworm
  stage: test
  allow_failure: true
  coverage: "/TOTAL.+ ([0-9]{1,3}%)/"
  variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/pip-cache"
  script:
    - pip install --upgrade pip>=25.0 setuptools>=78.1.1
    - pip install poetry
    - poetry config virtualenvs.create false
    - poetry install --with dev
    - make test-cov
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
  cache:
    key: "$CI_JOB_NAME"
    paths:
      - pip-cache/

# Security scan
security-scan:
  image: python:3.9-bookworm
  stage: test
  variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/pip-cache"
  script:
    - pip install --upgrade pip>=25.0 setuptools>=78.1.1
    - pip install poetry pip-audit bandit
    - poetry config virtualenvs.create false
    - poetry install --only main
    - pip-audit --desc --ignore-vuln GHSA-48p4-8xcf-vxj5 --ignore-vuln GHSA-pq67-6m6q-mj2v --ignore-vuln GHSA-3ww4-gg4f-jr7f --ignore-vuln GHSA-9v9h-cgj8-h64p --ignore-vuln PYSEC-2024-225 --ignore-vuln GHSA-h4gh-qq45-vh27 --ignore-vuln GHSA-79v4-65xg-pq4g
    - bandit -r cio_lambda_proxy/
  cache:
    key: "$CI_JOB_NAME"
    paths:
      - pip-cache/
  allow_failure: true
